version: '3'
services:
  mongodb-app:
    image: pranali456/hospital-management-system:1.0.0
    ports:
      - "8083:8083"
      environment:
        spring.data.mongodb.uri: mongodb://mongodb:27017/hospitalsystem
        depends_on:
          - mongodb
       networks:
          - mongodb-network
        mongodb:
          image: mongodb:3.4.7
          ports:
            - "27017:27017"
          networks:
            - mongodb-network
      networks:
        mongodb-network:
          driver: bridge
